name: C++ CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential
          sudo apt-get install -y libgtest-dev
          # Simple GTest installation - works with modern Ubuntu
          cd /usr/src/googletest
          sudo cmake .
          sudo make
          sudo cp lib/libgtest*.a /usr/lib/

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS_ONLY=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: Run Tests Directly
        working-directory: ${{github.workspace}}/build/bin
        run: |
          ./vectors_test
          ./matrix_test
